### ISSUE TITLE
Ep 02 | Resampling

### ISSUE THREAD

**Issue by josephmje** [jerdra/scwg2018_python_neuroimaging#16]
- [x] add photo example of resampling (can we make or find a gif?)
- [x] explain what 'normalization' is

**Comment by ostanley** [comment]
Hey guys, sorry I need some clarification. Do you mean normalization to a template? If so that is in the slides. Do we want to represent that in the notebook as well?

**Comment by jerdra** [comment]
Hi Olivia, yes standardization! I think we should mention it again when we start doing the group analysis with FC since it would make sense to do so with that. 

I think for this episode the pre-processing slides should be good enough. Closing this issue, feel free to re-open if you have additional thoughts!
